apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag-system
data:
  API_BASE_URL: "http://backend:3456"
  BACKEND_PORT: "3456"
  FLASK_ENV: "production"
  MONGO_DB: "rag_db"
  RAG_APP_PORT: "5000"
  REDIS_HOST: "redis"
