apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-app-data
  namespace: rag-system
spec:
  storageClassName: oci-bv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: rag-system
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: oci-bv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: rag-system
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: oci-bv
